### ISSUE TITLE
Manque de voix après combat Léon

### ISSUE THREAD

**Issue by Aiola13** [Noxalus/KHFM-VF-Patch#1]
Bonjour x),

Après le combat de Léon, lorsque Riku se réveille (je n'ai pas la time line sry), Riku crie "Sora ! Kairi !" . Les sous-tires sont bien présents mais pas de voix. Je ne sais plus si sur la version PS2 les voix sont présentes en VF ni en VO.

Voici un lien video [https://youtu.be/QP2yNFGnZv0](https://youtu.be/QP2yNFGnZv0)

**Comment by Fotia13** [comment]
Il n'y a jamais eu de voix pour cette scène vu que c'est une scène de la version final mix que ce soit en anglais ou français et pas de possibilité de rajouter une voix.

**Comment by Aiola13** [comment]
ça marche x) sorry de l'erreur j'ai pas vérifié avant.
