### ISSUE TITLE
Malware dans la 1.3 

### ISSUE THREAD

**Issue by Snipy44** [Noxalus/KHFM-VF-Patch#12]
![image](https://github.com/Noxalus/KHFM-VF-Patch/assets/3805333/fb883486-abb1-41d1-8402-a690ec6dea6c)

Hello, je tenais à vous signaler ceci ^^"

**Comment by Noxalus** [comment]
Oh wow, je n'ai jamais rencontré ce genre de problème et tout ce qui se trouve dans le patch est du code très simple 🤔 

Je ne sais pas ce qui peut être considéré comme un malware là-dedans et c'est techniquement impossible d'intégrer un malware au patch puisque tout le code source est en clair sur le repo et que la build est faite (et uploadée) par le bot GitHub une fois l'action terminée ([ici](https://github.com/Noxalus/KHFM-VF-Patch/actions/runs/9683134327)).

Quel est le logiciel qui remonte cette erreur ?

La 1.3.0 est une version de test que j'ai fait pour le Steam Deck, et qui ne fonctionne de toute façon pas comme attendu...

Est-ce que ça détecte la même chose pour la version 1.2.2 ? ([ici](https://github.com/Noxalus/KHFM-VF-Patch/releases/download/1.2.2/KHFM-VF-Patch-1.2.2.zip))

**Comment by Snipy44** [comment]
En tous cas sur la version 1.2.2 je n'avais pas ce soucis
le logiciel ces malwarebytes, tu peu le testé gratuitement pendant 30 jours

**Comment by Noxalus** [comment]
OK, la seule modification importante est le changement de la version de .NET demandée (car .NET 5 ne sera bientôt plus supporté).

Je vais tester de mon côté pour essayer de comprendre pourquoi il considère cela comme un malware.

Merci pour la remontée en tout cas 🙏

**Comment by Snipy44** [comment]
je t'en pris, merci à toi pour tout ce que tu nous partage !

**Comment by Noxalus** [comment]
Pour info, j'ai changé beaucoup de choses dans la façon dont le patch est construit dans la version [2.0.0](https://github.com/Noxalus/KHFM-VF-Patch/releases/tag/v2.0.0), il est possible que le problème soit résolu 😲

**Comment by Snipy44** [comment]
Je vais essayer merci !

**Comment by Snipy44** [comment]
Tout semble fonctionner, des nouvelles par rapport au video ou il manque des frames/fps en jeu?

**Comment by Noxalus** [comment]
Parfait, je ferme ce ticket alors 🙏 

Pour les vidéos, c'est un autre problème, et ça risque d'être un peu plus long à résoudre malheureusement 😅 

Ce que je peux essayer de faire en attendant, c'est laisser la possibilité ou non de les patcher, comme ça au moins ça ne dégrade pas les vidéos (même si elles resteront en anglais)
