### ISSUE TITLE
Erreur de patch

### ISSUE THREAD

**Issue by Piwice** [Noxalus/KHFM-VF-Patch#13]
Bonjour, excusez moi si cela a déjà été demandé, mais j'ai un problème lorsque j'essaye de patcher mon jeu, un message d'erreur apparait 

![image](https://github.com/Noxalus/KHFM-VF-Patch/assets/175115608/6ad7140c-db6c-4f09-95dd-f9dcf2ff4213)

Est ce que quelqu'un aurait une solution s'il vous plait ? 

Merci

**Comment by DopinoOff** [comment]
J'ai le même problème, je comprend pas comment faire :/

**Comment by Noxalus** [comment]
Bonjour, avez-vous tous les 2 utilisé la version 2.0.0 du patch ? 🤔 

Je pense savoir d'où vient le problème, je corrige ça dès que possible.

En attendant, pour patcher la version PC Steam vous devriez pouvoir utiliser la version [1.2.2](https://github.com/Noxalus/KHFM-VF-Patch/releases/download/1.2.2/KHFM-VF-Patch-1.2.2.zip) !

Désolé pour la déconvenue... 😓 (et merci pour la remontée 🙏 )

**Comment by Piwice** [comment]
Oui j'utilise bien la version 2.0.0
J'ai tenter de réinstaller le jeu mais ça n'a pas marcher
Je vais mettre la 1.2.2 en attendant
Merci beaucoup 😊

**Comment by Noxalus** [comment]
Je viens de faire la correction, effectivement j'avais oublié un point essentiel 😓 

La 2.0.1 est en train de build [ici](https://github.com/Noxalus/KHFM-VF-Patch/actions/runs/9864270562/job/27238852606), ça devrait résoudre le problème que vous rencontriez :/

**Comment by Noxalus** [comment]
C'est bon, elle vient de sortir, c'est ici: https://github.com/Noxalus/KHFM-VF-Patch/releases/tag/v2.0.1

J'en ai profité pour rajouter une option pour ne pas patcher les vidéos, il semblerait y avoir des problèmes de lags pour le moment, et j'aimerais trouver une approche.

**Comment by Piwice** [comment]
Super, merci beaucoup pour la reactivité

**Comment by Piwice** [comment]
ça marche nickel, merci beaucoup, bonne soirée

**Comment by Noxalus** [comment]
Merci pour le test, et bonne soirée ;)
