### ISSUE TITLE
Une erreur s'est produite. Acces to the path is denied

### ISSUE THREAD

**Issue by Mooddjo** [Noxalus/KHFM-VF-Patch#3]
Bonjour, 

A l'installation du patch, j'ai une erreur "**Une erreur s'est produite. Acces to the path is denied**". J'ai tenté de lancer le patch en admin mais même chose.
Mon path d'install étant le suivant: D:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX
Cela arrive, juste après l'exrtaction des fichiers.

**Comment by Mooddjo** [comment]
Il semble qu'il fallait lancer le jeu une 1er fois :)

**Comment by Noxalus** [comment]
Merci pour l'info, j'ignorais qu'il y avait ce genre de problème ! 🙏 

Cela pourrait aider d'autres personnes 👍
