### ISSUE TITLE
Erreur: Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by ToadBe** [Noxalus/KHFM-VF-Patch#4]
Bonsoir!
J'ai telechargé le patch et en le lancant, le patch bloque sur 
Une erreur s'est produite: Exception of type 'System.OutOfMemoryException' was thrown.

La VF a fonctionné jusque dans la ville de traverse, et s'est arreté après une cinématique avec Donald et Dingo...

Savez-vous quel est le problème ?
Merci à vous!

**Comment by Noxalus** [comment]
Bonsoir !

C'est étonnant que le jeu ait réussi à se lancer sans que le patch n'ait été appliqué jusqu'au bout 🤔 

L'erreur semble indiquer qu'il n'y a pas assez d'espace sur votre disque, les fichiers du jeu sont très lourd (> 5Go) et une copie est faite avant l'application du patch pour être sûr de ne pas casser le jeu si cela se passe mal. Si vous êtes un peu léger sur l'espace qu'il reste sur votre disque, vous pouvez décocher la case qui permet de sauvegarder les fichiers d'origine, mais c'est à vos risques et périls ! (le danger étant de devoir retélécharger l'ensemble des 50 Go)

**Comment by ToadBe** [comment]
Bonsoir! 
J'ai justement plus de 100 Go de libre sur mon disque dur, et même si je décoche la dernière case, il me fait quand même l'erreur :/

La version 32bit est elle différente que la version 64bit du patcher ? j'ai téléchargé la version 64bit mais j'ai vu que la version 32bit enlevait certaines partie de la VF. C'est peut-être ça la solution mais j'aimerais quand même avoir toutes les voix du jeu...

**Comment by Noxalus** [comment]
Il n'y a normalement aucune différence entre la version 32 bit et 64 bits !

Savez-vous à quelle étape du patch se produit l'erreur ? (et si c'est systématiquement au même moment ?)

Est-ce qu'un fichier de log a été généré dans le dossier du patch suite à l'erreur ?

**Comment by ToadBe** [comment]
Alors j'ai du coup essayé avec la version 32bit, et CA MARCHE !
Je ne comprend cependant pas pourquoi le patcher 64bit ne fonctionne pas, pourtant j'ai un ordinateur assez haut de gamme...
Désolé d'avoir dérangé alors que c'était juste un test de que je devais faire ^^'
Merci beaucoup pour l'aide !
