### ISSUE TITLE
Problème d'exécution .exe

### ISSUE THREAD

**Issue by HozSensei** [Noxalus/KHFM-VF-Patch#5]
Bonjour !
Avant tout, merci pour le travail fourni :D J'espère fixer mon soucis et profiter de ce jeu comme je l'ai découvert il y'a des années !
Voici mon soucis, lorsque je clique sur : KHFM-VF-Patch.exe
J'ai une popup d'erreur qui me dit : "To run this application, you must install .NET . Would you like to download it now?"
Si je met oui je suis redirigé vers ce site windows : [Lien windows](https://dotnet.microsoft.com/en-us/download/dotnet/5.0/runtime?utm_source=getdotnetcore&utm_medium=referral)
Dans le doute j'ai installer les 2 premiers truc mais ca ne marche toujours pas, j'ai toujours le message d'erreur :/
Une idée?
D'avance merci !

**Comment by Noxalus** [comment]
Bien le bonjour !

Merci pour le retour !

A priori, en installant [ceci](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.14-windows-x64-installer), cela devrait être bon 🤔

**Comment by HozSensei** [comment]
Désolé de répondre que maintenant !
J'ai finalement réussi a fixé le soucis en installant la version 32-bit (x86)...
Je ne sais pas pourquoi cela a solutionner mais le principal étant que maintenant j'ai le jeu en français ! Tout grand merci pour ce boulot !

**Comment by Noxalus** [comment]
Merci à toi pour l'info, je vais rajouter cela au README pour les gens qui auraient le même problème 👍
