### ISSUE TITLE
Indication de manque d'espace

### ISSUE THREAD

**Issue by Keldium** [Noxalus/KHFM-VF-Patch#6]
Bonjour ! J'utilise ce patch sur Steam OS en utilisant wine, j'ai plus de 100 giga de libres sur mon disque et pourtant l'application ne cesse de me répéter qu'il n'y a pas assez de place pour quatre malheureux giga... Je ne m'y connais pas vraiment en code et en modding, je viens donc demander de l'aide ici !

**Comment by Noxalus** [comment]
Bonjour !

Je n'ai jamais essayé d'installer le patch sur Steam OS, mais c'est un test intéressant, merci pour l'avoir remonté !

Ce que je peux dire, c'est que le patch va d'abord regarder si le jeu est installé dans son dossier par défaut, à savoir `C:\Program Files\Epic Games\KH_1.5_2.5`, si ce n'est pas le cas, il va demander d'indiquer où le jeu est installé. Est-ce que ce fut votre cas ?

Une fois le répertoire du jeu spécifié, le patch va alors s'assurer que le disque sur lequel se trouve le dossier en question a suffisamment d'espace (4 Go), si vous avez 100 Go sur un autre disque, le patch ne saura pas les utiliser aujourd'hui 🤔

**Comment by Keldium** [comment]
Oui, le patch m'a demandé où le jeu était installé, et je lui ai indiqué le chemin (qui se trouve sur le disque du deck où il y a 100giga de place).
J'ai été voir les autres "dossiers" (excusez mon langage de noob eheh) et le seul qui ne peut contenir 4go est... le dossier rootfs.

**Comment by Noxalus** [comment]
L'API qui retourne l'espace sur le disque ne marche peut-être pas aussi bien sur Steam OS.

A la base cette vérification permet de sauvegarder les fichiers originaux avant de les modifier afin de pouvoir retirer le patch facilement, mais là on est dans un cas où ce serait quand même pratique de pouvoir ignorer cette vérification, quitte à retélécharger tous les fichiers en cas de pépins.

Je vais essayer de rajouter un bouton à l'interface pour éviter la sauvegarde coup 👍

**Comment by Keldium** [comment]
Merci beaucoup !

**Comment by Noxalus** [comment]
C'est fait, vous trouverez la nouvelle version ici: https://github.com/Noxalus/KHFM-VF-Patch/releases/tag/1.2.1

N'hésitez pas à me dire si cela fonctionne comme il faut !

**Comment by Keldium** [comment]
Tout est parfait, le patch fonctionne !
