### ISSUE TITLE
Prévu pour KH II Final Mix ?

### ISSUE THREAD

**Issue by MarchandDeSable420** [Noxalus/KHFM-VF-Patch#7]
Bonjour bonjour !

Alors j'ai découvert ce patch juste après avoir fini KH I malheureusement...
J'étais persuadé qu'il prenait en compte les deux jeux donc je viens de l'installer, mais quand je lance KH II, surprise, ben ça marche pas :'(
 As tu prévu de rendre ce patch compatible avec KH II ou c'est pas du tout en projet ? J'adorerais retrouver les voix de mon enfance <3

**Comment by Noxalus** [comment]
Bonjour ! 👋 

Désolé pour le délai de ma réponse, il était prévu que le patch supporte les 2 jeux, mais un membre de l'équipe a sorti un patch avant trouvable ici: https://www.nexusmods.com/kingdomhearts2finalmix/mods/34

Du coup ce n'était pas vraiment la peine que je passe plus de temps sur ce projet 👍
