### ISSUE TITLE
Patch vf pour steamdeck

### ISSUE THREAD

**Issue by Radiaaaa** [Noxalus/KHFM-VF-Patch#9]
Bonjour, 

j'ai essayé d'installer sur mon Steam Deck mais c'est impossible déjà pour ouvrir un exe c'est un peu complique mais je suis bloquée ou il faut choisir les fichiers du jeu car ces fichiers sont "cachés".

je voudrais savoir si il y a une version Steam Deck de prévue.

**Comment by Jupitoup** [comment]
Salut, ouai ce serait super cool, perso quand je lance le patch .exe via l'ajout des jeux non steam ça me demande d'installer .NET 5 mais j'arrive pas à l'installer sur steamos ou meme en contournant via Protontricks.

Donc ouai une technique ou version pour l'installer sur steamdeck ce serait super cool ! Et merci pour le boulot quel plaisir de refaire ces jeux !

**Comment by JMauperin** [comment]
Doit sûrement moyen de préparer les fichiers sur pc puis de les transférer sur le deck je pense... Faut juste savoir quels fichiers transférer

**Comment by Noxalus** [comment]
Je vais sans doute pouvoir mettre la main sur un Steam Deck cette semaine, je pourrais faire des tests, il y a probablement une manière un peu simple de régler le problème 👍

**Comment by Radiaaaa** [comment]
> Je vais sans doute pouvoir mettre la main sur un Steam Deck cette semaine, je pourrais faire des tests, il y a probablement une manière un peu simple de régler le problème 👍

Merci beaucoup chef

**Comment by Jupitoup** [comment]
> Je vais sans doute pouvoir mettre la main sur un Steam Deck cette semaine, je pourrais faire des tests, il y a probablement une manière un peu simple de régler le problème 👍

Wouah merci !

**Comment by Frohlemageblanc** [comment]
Travail incroyable. J'allais justement chercher si une version steam deck du patch etait prevue :p

**Comment by Noxalus** [comment]
J'ai pu mettre la main sur un Steam Deck, je ne vais pas pouvoir faire de tests avant demain soir, mais je vais faire en sorte que ce soit corrigé avant samedi 👍

**Comment by Jupitoup** [comment]
Génial trop hâte de pouvoir continuer ma partie sur steam deck, merci encore !

**Comment by Noxalus** [comment]
Bon, pour une raison indépendante de ma volonté, je ne peux pas me connecter avec mon compte Steam sur le Steam Deck que j'ai obtenu, mais j'ai quand même pu faire quelques tests, et je pense qu'en réalité le patch pourrait déjà fonctionner en l'état sur le Steam Deck.

J'ai quand même fait une version qui va directement regarder le bon chemin du dossier de KH sur le Steam Deck ce qui évitera d'aller le chercher à la main, mais comme je l'ai dit avant, je n'ai pas pu le tester: https://mega.nz/file/sx9CHQRb#Nnd89FRVVIAUGJWY02OZLkL4G8fxQq_uhpsXF7XBMx8 😭 

Si jamais l'un de vous à le temps, je ne suis pas contre un feedback 🙏 De mon côté je pourrais seulement tester à partir de mercredi soir prochain :/

Mais sinon, ce que j'ai fait pour lancer la dernière version du patch, ça a été de lancer le Steam Deck en [mode desktop](https://help.steampowered.com/fr/faqs/view/671A-4453-E8D2-323C) puis d'installer Wine depuis le gestionnaire d'applications. J'ai ensuite téléchargé la [dernière version du patch](https://github.com/Noxalus/KHFM-VF-Patch/releases/download/1.2.2/KHFM-VF-Patch-1.2.2.zip) que j'ai pu lancer grâce à Wine en double cliquant dessus. 
Au premier lancement il me met un message d'erreur parce que .NET 5.0 n'est pas installé, je clique sur le bouton pour le télécharger et je le lance avec Wine également, l'installation se passe sans accroc, et en relançant le patch j'ai bien la fenêtre qui se lance.
Par contre du coup il me dit qu'il ne trouve pas le dossier du jeu (ce qui ne devrait pas être le cas avec la version que j'ai linké dans ce message), mais on peut aller chercher le dossier à la main. Le problème c'est que Wine n'affiche pas les dossiers cachés et donc on ne peut pas naviguer dans le dossier `.local` qui fait parti du chemin où se trouve les fichiers du jeu. La solution ça peut être d'aller directement dans le dossier du jeu depuis Steam (en cliquant sur le bouton pour accéder aux fichiers locaux de KH) puis de copier le chemin dans la barre d'adresse, mais il faut alors remplacer tous les `\` par des `/`, et comme je ne pouvais de toute façon pas installer le jeu sur le Steam Deck que j'ai, je n'ai pas poursuivi le test dans cette direction.

**Comment by Radiaaaa** [comment]
Coucouuuu, merci beaucoup, ça a fonctionné. Par contre, ça n'a pas trouvé les fichiers tout seul. J'ai dû les copier/coller en inversant les / et ça a marché. Merci t'es vraiment le boss <<333

**Comment by Buffshark** [comment]
Bonjour, alors perso je n'ai plus le probleme de localisation du dossier, par contre quand je commence a patcher le jeu, quelque seconde apres ca s'arrete en me disant "Une erreure est survenue. external component has thrown an exception" Que faire?

**Comment by Noxalus** [comment]
Cela ressemble pas mal au problème rencontré sur [cette issue](https://github.com/Noxalus/KHFM-VF-Patch/issues/10#issuecomment-2178950350), et le problème était lié au fait que la version de .NET n'était pas bonne, il faut manifestement la version 5.0.17. 🤔

**Comment by Buffshark** [comment]
J'ai pourtant bien la bonne version de .NET :/

**Comment by Noxalus** [comment]
Pour info j'ai écrit une petite page de doc sur comment installer le patch sur Steam Deck: https://github.com/Noxalus/KHFM-VF-Patch/wiki/Installation-du-patch-sur-Steam-Deck

J'ai aussi retravaillé pas mal de petites choses qui pourraient avoir un impact su l'erreur que tu as @Buffshark, mais j'attends de pouvoir vraiment tester de mon côté sur un Steam Deck physique (d'ici mercredi soir prochain) avant de publier une nouvelle version.

**Comment by Buffshark** [comment]
D'acc, j'ai retesté plusieurs fois avec differente version de .NET mais rien n'y fait, ca patch quelque seconde et l'erreur survient. A voir si tu arrive a reproduire mon probleme et de voir ce qui le declenche. Merci pour tes efforts en tout cas

**Comment by Buffshark** [comment]
Bon au final j'ai fait la solution un peu yolo, j'ai patché le jeu sur mon pc, et pendant le patching j'ai vu quel fichiers ont été patché, du coup j'ai juste copié ces fichiers la dans mon google drive et tout re dl et remplacé sur mon steam deck, ca marche nickel. Merci pour le taf initial du patch en tout cas, j'ai connu KH seulement avec les voix anglaise, donc entendre Donald Reignoux sur Sora fait un ptit quelque chose, surtout qu'a cette epoque la il a le timbre de voix de quand il doublait Reese dans Malcolm. Puis avoir les vrai VF de disney est très cool aussi, vraiment merci pour le taf :)

**Comment by Jupitoup** [comment]
Parfait merci beaucoup j'ai suivi les instructions et ça a marché ! Quel plaisir de refaire ce premier kh en VF merci encore pour tout !

**Comment by Noxalus** [comment]
> [Buffshark](/Buffshark)

C'est aussi une solution, mais je vais quand même faire le test demain quand j'aurais enfin accès au jeu !

Merci pour les infos en tout cas ! 🙏

**Comment by ElderLink** [comment]
![Screenshot_20240627_180237](https://github.com/Noxalus/KHFM-VF-Patch/assets/13025218/a3f2ce87-5ce4-4aee-a427-7b8adb85b875)
Bonjour, j'ai voulu suivre les solutions que vous avez évoqués, mais je me prends toujours le même message d'erreur, disant "File don't exist" et ce message d'erreur dans l'installateur.
Le jeu est installé sur le SSD du Steam Deck, je n'ai pas encore fait de lancement initial.

**Comment by Noxalus** [comment]
Avez-vous essayé d'utiliser la version [1.3.0](https://github.com/Noxalus/KHFM-VF-Patch/releases/download/v1.3.0/KHFM-VF-Patch-1.3.0.zip) ?

J'ai fait des tests hier avec une nouvelle version du patch sur le Steam Deck avec le jeu installé sur une carte SD, je n'ai pas réussi non plus de mon côté, je pense qu'il faut que je change de méthode, je vais voir ce que je peux faire dès que j'aurais un peu de temps.

En attendant, la solution de @Buffshark peut fonctionner si vous avez un PC à côté, à savoir patcher les fichiers du jeu sur PC et les transférer sur le Steam Deck au bon endroit. Les fichiers à récupérer après avoir exécuté le patch sur PC se trouvent dans le dossier `steamapps\common\KINGDOM HEARTS -HD 1.5+2.5 ReMIX-\Image\dt` et sont ceux-là:

![image](https://github.com/Noxalus/KHFM-VF-Patch/assets/1321964/76be0a49-694f-4a7b-a240-b4f7adeccc8c)

**Comment by Noxalus** [comment]
Bon, la version 1.3.0 ne marchant pas, j'ai regardé ce que je pouvais faire pour résoudre le problème et j'ai enfin eu une peu de temps pour me pencher dessus.

La solution vers laquelle je me suis dirigé a été de porter le code du patch sur [Avalonia UI](https://avaloniaui.net/) qui permet, sans trop de modification, de rendre une application bureau Windows disponible sur d'autre plateformes nativement (comme Linux ou MacOS).

Dis comme cela, ça paraît simple, mais ça m'a quand même demandé pas mal de temps pour avoir quelque chose qui tourne correctement sous Linux... 😓 

Mais j'y suis parvenu, et [la nouvelle version du patch](https://github.com/Noxalus/KHFM-VF-Patch/releases/tag/v2.0.0) peut être lancée directement sur le Steam Deck sans avoir à passer par Wine 🎉 

J'ai fait une petite vidéo de la marche à suivre ici: https://www.youtube.com/watch?v=AuUnATQ0zqc

Du coup je ferme ce ticket !
